// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/dashboard/Aurora.tsx": () => import("../components/mockups/dashboard/Aurora.tsx"),
  "./components/mockups/dashboard/Pulse.tsx": () => import("../components/mockups/dashboard/Pulse.tsx")
};
