// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/case-file-os/CaseMap.tsx": () => import("../components/mockups/case-file-os/CaseMap.tsx"),
  "./components/mockups/case-file-os/CommandPalette.tsx": () => import("../components/mockups/case-file-os/CommandPalette.tsx"),
  "./components/mockups/case-file-os/Showcase.tsx": () => import("../components/mockups/case-file-os/Showcase.tsx"),
  "./components/mockups/case-file-os/ShowcaseDark.tsx": () => import("../components/mockups/case-file-os/ShowcaseDark.tsx"),
  "./components/mockups/dashboard/Aurora.tsx": () => import("../components/mockups/dashboard/Aurora.tsx"),
  "./components/mockups/dashboard/Pulse.tsx": () => import("../components/mockups/dashboard/Pulse.tsx"),
  "./components/mockups/lf-dark-mobile/Dashboard.tsx": () => import("../components/mockups/lf-dark-mobile/Dashboard.tsx"),
  "./components/mockups/whitelabel/AdminDashboard.tsx": () => import("../components/mockups/whitelabel/AdminDashboard.tsx"),
  "./components/mockups/whitelabel/ClientPortal.tsx": () => import("../components/mockups/whitelabel/ClientPortal.tsx"),
  "./components/mockups/whitelabel/LDv1CommandCenter.tsx": () => import("../components/mockups/whitelabel/LDv1CommandCenter.tsx"),
  "./components/mockups/whitelabel/LDv2TodayFocus.tsx": () => import("../components/mockups/whitelabel/LDv2TodayFocus.tsx"),
  "./components/mockups/whitelabel/LDv3ClientCRM.tsx": () => import("../components/mockups/whitelabel/LDv3ClientCRM.tsx"),
  "./components/mockups/whitelabel/LDv4AICopilot.tsx": () => import("../components/mockups/whitelabel/LDv4AICopilot.tsx"),
  "./components/mockups/whitelabel/LawyerDashboard.tsx": () => import("../components/mockups/whitelabel/LawyerDashboard.tsx")
};
